[package]
name = "LIF_traffic_light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustupolis_server = "0.0.8"
rand = "0.8.5"
crossbeam = "0.8.1"